### ISSUE TITLE
Fading bed name when hovering?

### ISSUE THREAD

**Issue by jacoby** [drio/dnaism#2]
I told my coworkers about this project, and they are excited by it. An issue that has been brought up is that it's hard to read the numbers when you're looking at values far to the left, by the bed name. The axis labels fade out in context, so precedent is set.

**Comment by drio** [comment]
Hi Dave, 

Thanks for showing the project around and for bringing this up.

I see the problem. I'll put together a fix for that. We probably want to render the values in the other side of the vertical line in that case.
